### ISSUE TITLE
Bulk Import: drop the Recipient base URL input and always use HFS_BASE_URL

### ISSUE THREAD

**Issue by smunini** [HeliosSoftware/hfs#689]
## Summary

Remove the "Recipient base URL" input from the Create Bulk Submission dialog. The recipient base should always be the server's configured `HFS_BASE_URL`, not something the operator types per submission.

## Current behavior

`/ui/bulk-import` → "New Submission" asks the operator to type a Recipient base URL:

```html
<label class="field">
  <span class="field__label">{{ i18n.t("bulk-import-field-recipient") }}</span>
  <input class="field__input" type="url" name="recipient_base_url" required
         autocomplete="off" placeholder="http://localhost:8080">
  <span class="field__hint">{{ i18n.t("bulk-import-field-recipient-hint") }}</span>
</label>
```
— `crates/ui/templates/pages/bulk-import.html:28-33`

The typed value lands in `CreateForm.recipient_base_url` (`crates/ui/src/bulk_import.rs:291-296`), is stored on the submission (`:325-327`), rendered as "Data Recipient" on the detail page (`crates/ui/templates/pages/bulk-import-detail.html:64`), and is what every kick-off is POSTed to: `post_kickoff` builds `{recipient_base_url}/$bulk-submit` (`crates/ui/src/bulk_import.rs:673-676`) and `status_kickoff` builds `{recipient_base_url}/$bulk-submit-status` (`:698-701`).

Typing it by hand is how a submission ends up pointed at something that is not a Bulk Data Submit endpoint — see #686, where the base URL pointed at a static file server and every submit came back 501.

## Expected behavior

- The Create Bulk Submission dialog has no Recipient base URL field.
- Every submission's recipient base is the server's `HFS_BASE_URL`.
- The detail page still shows the recipient, read-only, so the operator can see where data is going.

## Evidence

- `crates/ui/templates/pages/bulk-import.html:28-33` — the input to remove
- `crates/ui/src/bulk_import.rs:291-296` — `CreateForm.recipient_base_url`
- `crates/ui/src/bulk_import.rs:325-327` — where the form value is stored on the submission
- `crates/ui/src/bulk_import.rs:673-676`, `:698-701` — the two kick-off URLs built from it
- `crates/rest/src/config.rs:918-920` — `HFS_BASE_URL` → `ServerConfig::base_url`, default `http://localhost:8080`
- `locales/en/main.ftl:557-558` — `bulk-import-field-recipient` and its hint, to remove from all three catalogs

## Suggested approach

**The value is not currently available to the UI crate.** `crates/hfs/src/main.rs:667` passes `helios_ui::mount` a `self_base_url` of `format!("http://127.0.0.1:{}", config.port)` — a loopback address used for the UI's own server-to-server conformance fetches, deliberately not `config.base_url`. `HFS_BASE_URL` is never handed to the UI today, and `WebState` (`crates/ui/src/lib.rs:106-125`) does not carry either value.

So the work is:

1. Pass `config.base_url` into `helios_ui::mount` as a new parameter (distinct from the existing `self_base_url`) and store it on `WebState`.
2. Drop `recipient_base_url` from `CreateForm` and set the submission's recipient from that state value in `create` (`crates/ui/src/bulk_import.rs:320-330`).
3. Remove the field from `crates/ui/templates/pages/bulk-import.html:28-33` and the two strings from `locales/{en,de,es}/main.ftl`.
4. Keep `Submission.recipient_base_url` as a stored field (`crates/ui/src/bulk_import.rs:44`) and keep rendering it on the detail page — submissions created before this change already carry a value, and the kick-off code reads the stored field either way. Decide whether existing submissions keep their stored recipient or are re-pointed at `HFS_BASE_URL` on next submit.
5. Check the e2e/unit tests that post to `/ui/bulk-import` with a `recipient_base_url` field.

Note that `HFS_BASE_URL` defaults to `http://localhost:8080`, so on a server where it was never set every submission will target localhost. If that is not wanted, the dialog should say what the resolved recipient is rather than leaving it invisible.

## Scope / out of scope

The Create Bulk Submission dialog and how the recipient base is sourced. Not in scope: the Add Manifest dialog, the submit/abort/complete flow, or the failure-reporting problems tracked in #686.
