### ISSUE TITLE
Transaction/batch Bundles ignore fhirVersion content negotiation and persist entries as compile-time default (R4); HFS_DEFAULT_FHIR_VERSION ineffective

### ISSUE THREAD

**Issue by dougc95** [HeliosSoftware/hfs#350]
## Summary

On the v0.2.1 release binary (all-features build), **transaction/batch Bundle processing ignores the request's `fhirVersion` MIME parameter and persists every bundle-created resource as the compile-time default version (R4)**, while single-resource endpoints honor the same negotiation correctly. `HFS_DEFAULT_FHIR_VERSION` (and `--default-fhir-version`) have no observable effect on `/metadata`, bundle processing, or the PostgreSQL backend. The combination makes it impossible to use atomic transactions with R5 resources on release binaries.

## Environment

- `hfs-0.2.1-x86_64-unknown-linux-gnu.tar.gz` (sha256 `31cc93e6…ed728`), tag `v0.2.1`, commit `93ead8a`
- PostgreSQL backend (`HFS_DATABASE_URL` set, postgres 16.14), Docker (debian:trixie-slim runtime)
- Env: `HFS_DEFAULT_FHIR_VERSION=R5`, `HFS_SERVER_HOST=0.0.0.0` (both visible in the container env; host binding IS honored, so clap env parsing itself works)

## Reproduction

1. **Single-resource create honors negotiation (works as expected):**

```bash
curl -X POST 'http://localhost:8080/Location' \
  -H 'Content-Type: application/fhir+json; fhirVersion=5.0' \
  -H 'Accept: application/fhir+json; fhirVersion=5.0' \
  -d '{"resourceType":"Location","name":"Probe"}'
# -> 201; subsequent GET with 'Accept: ...fhirVersion=5.0' -> 200 (R5)
# R5-only types (InventoryItem) also create fine this way.
```

2. **Transaction bundle with the SAME headers persists R4:**

```bash
curl -X POST 'http://localhost:8080/' \
  -H 'Content-Type: application/fhir+json; fhirVersion=5.0' \
  -H 'Accept: application/fhir+json; fhirVersion=5.0' \
  -d '{"resourceType":"Bundle","type":"transaction","entry":[{"fullUrl":"urn:uuid:11111111-1111-1111-1111-111111111111","resource":{"resourceType":"Location","name":"BundleProbe"},"request":{"method":"POST","url":"Location"}}]}'
# -> 200 transaction-response, entry 201 Created

curl 'http://localhost:8080/Location/<created-id>' \
  -H 'Accept: application/fhir+json; fhirVersion=5.0'
# -> 406 {"issue":[{"details":{"text":"Resource is FHIR 4.0 but 5.0 was requested"}}]}
```

3. **`HFS_DEFAULT_FHIR_VERSION=R5` / `--default-fhir-version R5` change nothing observable:** `/metadata` without an `Accept` version parameter still reports `"fhirVersion":"4.0.1"`; bundle persistence stays R4. (Tried values `R5`, `r5`, `5.0`, `5.0.0` and the CLI flag — no effect.)

## Root cause (v0.2.1 source)

- `batch_handler` extracts no FHIR version at all — no `FhirVersionExtractor` in its signature (`crates/rest/src/handlers/batch.rs:52-60`), unlike `create_handler` (`crates/rest/src/handlers/create.rs:56-78`) which uses `version.storage_version()`.
- Transaction path: `process_transaction` carries no version parameter; `PostgresTransaction::create` stamps `FhirVersion::default_enabled()` (`crates/persistence/src/backends/postgres/transaction.rs:194`). Batch path hardcodes `default_enabled()` in the REST handler (`batch.rs:392`, `:417`).
- `default_enabled()` is the **compile-time** first enabled feature (`crates/fhir/src/lib.rs:1878-1905`) — R4 in the all-features release build.
- `ServerConfig.default_fhir_version` (clap env `HFS_DEFAULT_FHIR_VERSION`, `crates/rest/src/config.rs:714-722`) is consulted only by search handlers (`crates/rest/src/handlers/search.rs:389`, `:471`). `/metadata` uses `accept_version().unwrap_or_else(default_enabled)` (`crates/rest/src/handlers/capabilities.rs:83-85`), and `start_postgres` builds the backend via `PostgresBackend::from_env()` which defaults `fhir_version` to `default_enabled()` — the configured value is never passed in (`crates/hfs/src/main.rs:1442-1461`; `crates/persistence/src/backends/postgres/backend.rs:147`, `:213-230`).

Checked against `main` (2026-07-23): all call sites unchanged, so this is not fixed by a newer build.

## Impact

Any deployment that needs **atomic transaction bundles with a non-R4 version** cannot use the release binaries: writes silently persist as R4, and later version-negotiated reads 406. It is easy to miss because single-resource CRUD negotiates correctly, so smoke tests pass and only bundle-based write paths are affected.

## Suggested fixes (either would resolve our case)

1. **Minimal**: make the configured default effective for bundles + metadata — use `state.config().default_fhir_version` in `batch.rs:392/417` and `capabilities.rs:85`, add a `fhir_version` field to `PostgresTransaction` populated from the backend config, and pass `ServerConfig.default_fhir_version` into backend construction in `start_postgres`. (~15 lines; we sketched this and can share a patch.)
2. **Complete**: plumb the request-negotiated version into bundle processing (add `FhirVersionExtractor` to `batch_handler` and a version parameter through `process_transaction`/`Transaction::create` across backends) so bundles behave like single-resource endpoints.

## Workaround we adopted

Single-version source build: `cargo build --release -p helios-hfs --no-default-features --features "R5,postgres"` — flips `default_enabled()` to R5 everywhere (bundles, `/metadata`, search-parameter file selection) with no source changes. Works, at the cost of losing multi-version support in one binary.

Happy to provide more detail, full logs, or a PR for option 1 if that direction is acceptable.

---
*Note: supersedes #349, which was filed from the wrong account and is being closed in favor of this one.*

**Comment by dougc95** [comment]
Correction to the "Workaround we adopted" section: the single-version build (`--no-default-features --features "R5,postgres"`) does **not** actually compile on v0.2.1, and could not have worked anyway.

`cargo tree -p helios-hfs --no-default-features --features R5,postgres -i helios-fhir -e features` shows `helios-audit`'s `R5` feature intentionally enables its `R4B` feature (BALP baseline, per the comment in `crates/audit/Cargo.toml`), which enables `helios-fhir/R4B`. Two effects:

1. `helios-sof` fails with `error[E0004]: non-exhaustive patterns: FhirVersion::R4B not covered` — the `R4B` variant exists (via `helios-fhir/R4B`) but sof's `#[cfg(feature = "R4B")]` match arms are compiled out because nothing forwards `helios-sof/R4B` on that path.
2. Even if it compiled, `enabled_versions()[0]` would be `R4B`, so bundles/metadata would default to R4B rather than R5.

So on v0.2.1 there is no feature combination that yields an R5 default while keeping `helios-audit`. Our actual workaround is a consistent `--features "R4B,R5,postgres"` build plus a one-function patch making `default_enabled()` prefer R5 when compiled in. This also suggests the sof feature graph has a latent gap: any crate that enables `helios-fhir/R4B` without `helios-sof/R4B` (as `helios-audit/R5` does) breaks the sof build.

**Comment by angela-helios** [comment]
Thanks for the exceptional report — every citation checks out on current main (the batch sites drifted to `batch.rs:399/427`).

We are treating this as three defects and taking all of them:

1. **Bundles ignore the negotiated version** (this issue) — going with your **option 2**: `FhirVersionExtractor` on `batch_handler`, and a `fhir_version` parameter threaded through `BundleProvider::process_transaction`/`process_batch` and `Transaction::create`/`update` across all five implementing backends (sqlite, postgres, mongodb, s3, composite), so bundle entries stamp exactly what single-resource endpoints stamp.
2. **Configured default ineffective as fallback** — your option 1, tracked in #355: `/metadata`, the extractor fallback, and backend construction will honor `ServerConfig.default_fhir_version`.
3. **sof feature-graph gap** from your follow-up comment — tracked in #356: sof already has a documented guard pattern for exactly this scenario at five sites; `cli.rs:404` and `handlers.rs:744` are missing it.

PRs for all three are in progress (2 lands first, 1 stacks on it so bundle fallback uses the configured default). No need for a patch on your side, but review is welcome.

**Comment by angela-helios** [comment]
All three PRs are up:

- #360 — bundles stamp the negotiated version (option 2; new regression test proves a transaction+batch POST with R5 reads back as R5). Stacked on #359.
- #359 — `HFS_DEFAULT_FHIR_VERSION` is the effective fallback for `/metadata`, `$versions`, single-resource writes, and PostgreSQL backend construction (option 1).
- #358 — the sof feature-graph guards (a third unguarded site, `models.rs`, surfaced when actually building your failing combination; `--no-default-features --features R5,postgres` now compiles).

With #359 + #360, your deployment can drop the source build: the release binary honors `fhirVersion=5.0` on bundles, and `HFS_DEFAULT_FHIR_VERSION=R5` covers everything that negotiates nothing.
